### ISSUE TITLE
Your device is not connected to the internet

### ISSUE THREAD

**Issue by 244GUN** [R3tr074/Burn-Byte#1]
Hello, I'd like to ask u something 
Why is this prompted：
Your device is not connected to the internet

Please help me to answer, thank u：）

**Comment by R3tr074** [comment]
I gonna add a -f(force) mode to ignore this error, thanks for feedback

**Comment by R3tr074** [comment]
commit with this alteration:
https://github.com/R3tr074/Burn-Byte/commit/6e82aa2d38460ffc299c387a652a1441aef49240
